[test]
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageThreshold = { lines = 0.85 }
coveragePathIgnorePatterns = ["packages/web/**", "**/dist/**", "**/sim/**"]
