// Embeds the sources the in-page editor needs — the SDK's assembly files, the three example
// programs (Mandelbrot, word count, hello) with their manifests, and the SDK's README as the
// editor's guide — as string constants in src/program-sources.generated.ts. The web build runs this
// first; the editor-core test fails when the committed file is stale.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "../../..");
const sdkDir = path.join(root, "packages/sdk-as/assembly");
const programDir = path.join(root, "programs/mandelbrot");
const wordcountDir = path.join(root, "programs/wordcount");
const helloFile = path.join(root, "packages/sdk-as/examples/hello.ts");
const readmeFile = path.join(root, "packages/sdk-as/README.md");
/** The hello example's manifest; the file itself is the SDK's example, not a shipped program. */
const HELLO_MANIFEST = {
  name: "hello",
  view: "text",
  description: "One task that says hello; the smallest program there is.",
  defaultParams: { who: "world" },
};
export const GENERATED = path.join(root, "packages/web/src/program-sources.generated.ts");

/** The generated module's text, built from the files on disk. */
export function renderSources(): string {
  const sdk: Record<string, string> = {};
  for (const name of readdirSync(sdkDir).sort()) {
    if (!name.endsWith(".ts")) continue;
    sdk[name] = readFileSync(path.join(sdkDir, name), "utf8");
  }
  const source = readFileSync(path.join(programDir, "assembly/index.ts"), "utf8");
  const manifest = readFileSync(path.join(programDir, "manifest.json"), "utf8");
  const wordcount = readFileSync(path.join(wordcountDir, "assembly/index.ts"), "utf8");
  const wordcountManifest = readFileSync(path.join(wordcountDir, "manifest.json"), "utf8");
  const hello = readFileSync(helloFile, "utf8");
  const readme = readFileSync(readmeFile, "utf8");
  const lines = [
    "// Generated by packages/web/scripts/gen-sources.ts from packages/sdk-as/assembly and",
    "// programs/mandelbrot — do not edit; run `bun packages/web/scripts/gen-sources.ts`.",
    "",
    "/** The SDK's AssemblyScript sources, by file name under assembly/. */",
    `export const SDK_FILES: Record<string, string> = ${JSON.stringify(sdk, null, 2)};`,
    "",
    "/** The Mandelbrot program as shipped, the editor's prefilled source. */",
    `export const MANDELBROT_SOURCE = ${JSON.stringify(source)};`,
    "",
    "/** Its manifest, as JSON text. */",
    `export const MANDELBROT_MANIFEST = ${JSON.stringify(manifest)};`,
    "",
    "/** Word count as shipped (three stages over /in/corpus.txt), and its manifest. */",
    `export const WORDCOUNT_SOURCE = ${JSON.stringify(wordcount)};`,
    `export const WORDCOUNT_MANIFEST = ${JSON.stringify(wordcountManifest)};`,
    "",
    "/** The SDK's hello example — the smallest program — and its manifest. */",
    `export const HELLO_SOURCE = ${JSON.stringify(hello)};`,
    `export const HELLO_MANIFEST = ${JSON.stringify(JSON.stringify(HELLO_MANIFEST))};`,
    "",
    "/** The SDK's README, the editor's guide: what a program is and what it may do. */",
    `export const GUIDE_MARKDOWN = ${JSON.stringify(readme)};`,
    "",
  ];
  return lines.join("\n");
}

/** Write the module when it differs from what is on disk; returns true when it changed. */
export function generateSources(): boolean {
  const text = renderSources();
  if (existsSync(GENERATED) && readFileSync(GENERATED, "utf8") === text) return false;
  writeFileSync(GENERATED, text);
  return true;
}

if (import.meta.main) {
  const changed = generateSources();
  console.log(
    `[gen-sources] ${path.relative(root, GENERATED)} ${changed ? "written" : "unchanged"}`,
  );
}
