// Embeds the sources the in-page editor needs — the SDK's assembly files and the Mandelbrot
// program with its manifest — as string constants in src/program-sources.generated.ts. The web
// build runs this first; the editor-core test fails when the committed file is stale.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "../../..");
const sdkDir = path.join(root, "packages/sdk-as/assembly");
const programDir = path.join(root, "programs/mandelbrot");
export const GENERATED = path.join(root, "packages/web/src/program-sources.generated.ts");

/** The generated module's text, built from the files on disk. */
export function renderSources(): string {
  const sdk: Record<string, string> = {};
  for (const name of readdirSync(sdkDir).sort()) {
    if (!name.endsWith(".ts")) continue;
    sdk[name] = readFileSync(path.join(sdkDir, name), "utf8");
  }
  const source = readFileSync(path.join(programDir, "assembly/index.ts"), "utf8");
  const manifest = readFileSync(path.join(programDir, "manifest.json"), "utf8");
  const lines = [
    "// Generated by packages/web/scripts/gen-sources.ts from packages/sdk-as/assembly and",
    "// programs/mandelbrot — do not edit; run `bun packages/web/scripts/gen-sources.ts`.",
    "",
    "/** The SDK's AssemblyScript sources, by file name under assembly/. */",
    `export const SDK_FILES: Record<string, string> = ${JSON.stringify(sdk, null, 2)};`,
    "",
    "/** The Mandelbrot program as shipped, the editor's prefilled source. */",
    `export const MANDELBROT_SOURCE = ${JSON.stringify(source)};`,
    "",
    "/** Its manifest, as JSON text. */",
    `export const MANDELBROT_MANIFEST = ${JSON.stringify(manifest)};`,
    "",
  ];
  return lines.join("\n");
}

/** Write the module when it differs from what is on disk; returns true when it changed. */
export function generateSources(): boolean {
  const text = renderSources();
  if (existsSync(GENERATED) && readFileSync(GENERATED, "utf8") === text) return false;
  writeFileSync(GENERATED, text);
  return true;
}

if (import.meta.main) {
  const changed = generateSources();
  console.log(
    `[gen-sources] ${path.relative(root, GENERATED)} ${changed ? "written" : "unchanged"}`,
  );
}
